// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "我的 App",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "我的 App",
            targets: ["AppModule"],
            bundleIdentifier: "MyDbApplication",
            teamIdentifier: "49XJ9L9WAK",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .localNetwork(purposeString: "在？看看内网", bonjourServiceTypes: ["New Service Type"])
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/willdale/SwiftUICharts", "2.9.6"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftUICharts", package: "SwiftUICharts")
            ],
            path: "."
        )
    ]
)
